"""Dataclasses for the knowledge base, ideas, themes, changelog, and run state.

Serialization is deliberately simple: ``asdict`` for writing and ``from_dict``
(which ignores unknown keys and fills missing ones with defaults) for reading.
This keeps the committed JSON forward/backward compatible as the schema evolves.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field, fields
from typing import Any, TypeVar

KB_SCHEMA_VERSION = 1

T = TypeVar("T")


def _from_dict(cls: type[T], data: dict[str, Any]) -> T:
    """Construct a dataclass from a dict, ignoring unknown keys."""
    known = {f.name for f in fields(cls)}  # type: ignore[arg-type]
    return cls(**{k: v for k, v in data.items() if k in known})  # type: ignore[call-arg]


# Canonical category keys used across the KB and site.
CATEGORIES = {
    "papers": "Papers",
    "safety": "Open-Ended AI Safety",
    "surveys": "Surveys and Perspectives",
    "blogs": "Blog Posts and Hacks",
    "videos": "Videos",
}


@dataclass
class Entry:
    """A single knowledge-base item: a paper, blog post, or video."""

    entry_id: str
    title: str
    authors: list[str]
    authors_raw: str
    venue: str | None
    year: int | None
    category: str
    links: dict[str, str]
    arxiv_id: str | None = None
    abstract: str | None = None
    abstract_source: str | None = None
    abstract_url: str | None = None
    arxiv_published: str | None = None
    arxiv_categories: list[str] | None = None
    pdf_path: str | None = None
    # Citation counts (Semantic Scholar); None = not fetched yet.
    citation_count: int | None = None
    influential_citation_count: int | None = None
    # Real-publication signals (arXiv is a preprint server, not a venue).
    journal_ref: str | None = None
    doi: str | None = None
    comment: str | None = None
    venue_display: str | None = None
    first_seen_utc: str | None = None
    last_seen_utc: str | None = None
    content_hash: str = ""
    source_repo: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Entry:
        return _from_dict(cls, data)


@dataclass
class Idea:
    """A research idea generated by AI-Scientist-v2, with provenance."""

    idea_id: str
    name: str
    title: str
    short_hypothesis: str
    related_work: str
    abstract: str
    experiments: str
    risk_factors_and_limitations: str
    run_id: str
    run_utc: str
    model: str
    source_sha: str | None = None
    generated: bool = True
    # Set when a newly-added upstream paper essentially realizes this idea.
    realized: bool = False
    realized_paper_title: str | None = None
    realized_paper_url: str | None = None
    realized_entry_id: str | None = None
    realized_score: float | None = None
    # GitHub-Issues voting/feedback backend (👍/👎 reactions + comments per idea).
    issue_number: int | None = None
    issue_url: str | None = None
    votes_up: int = 0
    votes_down: int = 0
    score: int = 0
    feedback_count: int = 0
    # Model-of-Interestingness score (0-1): how interesting the MOI judges this idea,
    # given the whole current corpus. Set by the offline-but-cheap moi.score step.
    moi_score: float | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Idea:
        return _from_dict(cls, data)


@dataclass
class Cluster:
    """A theme cluster from the consensus analysis."""

    id: int
    label: str
    size: int
    top_terms: list[str]
    representative_titles: list[str]
    members: list[dict[str, str]] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Cluster:
        return _from_dict(cls, data)


@dataclass
class ThemeReport:
    """Output of the consensus / majority-vote analysis layer."""

    generated_utc: str
    method: str
    n_docs: int
    top_keyphrases: list[dict[str, Any]] = field(default_factory=list)
    clusters: list[dict[str, Any]] = field(default_factory=list)
    themes_by_year: dict[str, dict[str, int]] = field(default_factory=dict)
    # Curated, sensible research concepts detected across the corpus.
    concepts: list[dict[str, Any]] = field(default_factory=list)
    consensus_statement: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ThemeReport:
        return _from_dict(cls, data)


@dataclass
class ChangelogEntry:
    """One pipeline run's worth of changes, appended to changelog.json."""

    run_id: str
    run_utc: str
    from_sha: str | None
    to_sha: str | None
    upstream_compare_url: str | None
    added: list[dict[str, str]] = field(default_factory=list)
    removed: list[dict[str, str]] = field(default_factory=list)
    changed: list[dict[str, Any]] = field(default_factory=list)
    counts: dict[str, int] = field(default_factory=dict)
    new_ideas: int = 0
    themes_changed: bool = False
    note: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ChangelogEntry:
        return _from_dict(cls, data)


@dataclass
class State:
    """Persisted state used to gate runs on upstream changes."""

    upstream_repo: str
    upstream_sha: str | None = None
    last_run_utc: str | None = None
    run_count: int = 0

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> State:
        return _from_dict(cls, data)
